### ISSUE TITLE
Hibas url-ek

### ISSUE THREAD

**Issue by balazsadam** [gklka/MagyarTV#1]
Sziasztok!

Par percel ezelott probaltam az appot, es sajnos nem indulnak el a streamek. Hibas HTML a hibauzenet.

Udv
balazsadam

**Comment by gklka** [comment]
Sajnos újra kéne írni a parsert, mert változott a HTML oldal. Nincs időm rá. :(

**Comment by balazsadam** [comment]
Igen, Sajnos lattam, beleneztem a kodba, es mar nem olyan egyszeru kiszedni a linket, 3x 4x kellene vegigmenni a linkeken. Sikerult par curl-el kiszedni, ha van vallalkozo szellemu, akkor annak segitek.

**Comment by gklka** [comment]
Ha konkrétan megvan, mit kéne ki-parse-olni, akkor jöhet, annyi időm talán van :D

**Comment by balazsadam** [comment]
itt egy kis help
https://superuser.com/questions/917642/how-to-capture-stream-from-mediaklikk-hu

holnap ha gondolod keressuk egymast, es segitek osszehozni.

**Comment by gklka** [comment]
Ez nem nagyon segít sajnos :(

**Comment by balazsadam** [comment]
1. ez adja a lejatszot:
http://player.mediaklikk.hu/player/player-inside-full3.php?userid=mtva&streamid=mtv1live&noflash=yes&hls=2

eddig megvolt, a kovetkezo

2. iteracio:

itt talalsz egy ilyet a valaszban : 
            pl.setup({"autostart":true,"width":"100%","aspectratio":"16:9","hlshtml":"true","advertising":{"client":"vast"},"playlist":[{"file":"http:\/\/c201-node62-cdn.connectmedia.hu\/1000\/27197541c9e076b3a4ddd2b7a5fbae64\/599299ea\/index.m3u8?v=5i"}]});

itt ez a lenyeg: http:\/\/c201-node62-cdn.connectmedia.hu\/1000\/27197541c9e076b3a4ddd2b7a5fbae64\/599299ea\/index.m3u8?v=5i

3. m3u fajlok

ha fenti linket meghivod, akkor kapsz 5-6 db m3u playlistet.

( 8:52:47)[28994 localhost :~/Downloads]# curl 'http://c201-node62-cdn.connectmedia.hu/1000/27197541c9e076b3a4ddd2b7a5fbae64/599299ea/index.m3u8?v=5i'
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=499754,CODECS="avc1.42c00d,mp4a.40.2",RESOLUTION=320x180
05.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=857363,CODECS="avc1.42c01e,mp4a.40.2",RESOLUTION=480x270
04.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1214971,CODECS="avc1.4d401e,mp4a.40.2",RESOLUTION=640x360
03.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1521493,CODECS="avc1.4d4028,mp4a.40.2",RESOLUTION=854x480
02.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2951928,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1280x720
01.m3u8

ha az egyik playlistet behivod akkor mar megkapod a ts streamek linkjeit:

( 8:53:24)[28995 localhost :~/Downloads]# curl 'http://c201-node62-cdn.connectmedia.hu/1000/27197541c9e076b3a4ddd2b7a5fbae64/599299ea/05.m3u8?v=5i'
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:8
#EXT-X-MEDIA-SEQUENCE:28746035
#EXT-X-KEY:METHOD=AES-128,URI="20170711T080348-05-28746035.hex",IV=0xA6B147FFE5CD8CAFC34BF770DEE33D26
#EXTINF:8, no desc
#EXT-X-PROGRAM-DATE-TIME:2017-08-15T06:54:18Z
20170711T080348-05-28746035.ts
#EXT-X-KEY:METHOD=AES-128,URI="20170711T080348-05-28746036.hex",IV=0x35BEAAB9DFBD8AC060906717FACF3AA6
#EXTINF:8, no desc
#EXT-X-PROGRAM-DATE-TIME:2017-08-15T06:54:26Z
20170711T080348-05-28746036.ts
#EXT-X-KEY:METHOD=AES-128,URI="20170711T080348-05-28746037.hex",IV=0x35BEAAB9DFBD8AC060906717FACF3AA6
#EXTINF:8, no desc
#EXT-X-PROGRAM-DATE-TIME:2017-08-15T06:54:34Z
20170711T080348-05-28746037.ts
#EXT-X-KEY:METHOD=AES-128,URI="20170711T080348-05-28746038.hex",IV=0x524BF2FB6FE3BBECAE196A6903624782
#EXTINF:8, no desc
#EXT-X-PROGRAM-DATE-TIME:2017-08-15T06:54:42Z
20170711T080348-05-28746038.ts
#EXT-X-KEY:METHOD=AES-128,URI="20170711T080348-05-28746039.hex",IV=0x524BF2FB6FE3BBECAE196A6903624782
#EXTINF:8, no desc
#EXT-X-PROGRAM-DATE-TIME:2017-08-15T06:54:50Z
20170711T080348-05-28746039.ts

**Comment by balazsadam** [comment]
Bonyolult lett, de legalabb idegesito :D

**Comment by gklka** [comment]
Javítottam.

**Comment by balazsadam** [comment]
Este megtesztelem.
