### ISSUE TITLE
Hibás HTML

### ISSUE THREAD

**Issue by kelemenandras** [gklka/MagyarTV#2]
A csatornák nem jönnek be, helyette a következő hiba jelenik meg:

Hálózati hiba
(A hibachi oka: Hibás HTML)

**Comment by gklka** [comment]
Felraktam egy fejlesztett verizót, amiben néhány csatorna újra megy. Sajnos a Duna és az M4 DRM-mel van ellátva, azokat nem tudom hogy kéne lejátszani.

**Comment by kelemenandras** [comment]
Köszönöm a gyors segítséget. Ahogy írtad, a három csatorna megjavult. A DRM-mel kapcsolatban sajnos nem tudok segíteni. Ha jól értem a DRM működését, akkor a szolgáltatónak kellene engedélyeznie az Apple TV-t, vagy az app-et, hogy lejátszhassa a stream-et.

**Comment by gklka** [comment]
A nem DRM csatornáknál a HTML fájl tartalmaz egy playlist részt, ebben közvetlenül szerepel a stream URL-je. A DRM-es esetben a playlist jóval összetettebb, mindenféle kulcsokat tartalmaz; nem volt sajnos időm és energiám utánajárni, hogy hogy lehetne ezt lejátszani. Feltételezem amúgy, hogy meg lehetne csinálni.

**Comment by kelemenandras** [comment]
Időközben megnéztem a hivatalos Mediaklikk app-et az iPhone-on. Ott megy a Duna és az M5, de az M4 Sport innen svájcból nem elérhető (EZ A TARTALOM CSAK MAGYARORSZÁGON ÉRHETŐ EL). Ezt mondjuk egy VPN-nel ki tudnám küszöbölni. 

Hogyan tudod megnézni a HTML fájl tartalmát? Esetleg én is vetnék rá egy pillantást, habár ilyennel még én sem foglalkoztam.

**Comment by gklka** [comment]
Kiírja debug logba, ha Xcode-ból futtatod az appot.
