### ISSUE TITLE
IPA release?

### ISSUE THREAD

**Issue by razhun** [gklka/MagyarTV#3]
Varhato elore buildelt release, amit csak ujra kell szignozni? Egyszerubb lenne peldaul AltStore-ral hasznalni, mint igy, hogy kezzel kell buildelni is.

**Comment by gklka** [comment]
Hogy raktál AltStore-t az AppleTV-re? :)

**Comment by razhun** [comment]
Sorry, kicsit kevertem a neveket, AltServerre gondoltam. A Beta tud sideloadolni Apple TV-re.

**Comment by gklka** [comment]
Csak azért, mert ez engem is érdekelne :D Release-t rakok ki, pár perc.

**Comment by gklka** [comment]
Kiraktam a binárisokat a release oldalra: https://github.com/gklka/MagyarTV/releases/tag/version%2F2.0
